# Generated by Django 5.1.4 on 2025-01-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="agreement",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="signup",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
